### ISSUE TITLE
After I updated the miniserver to 13.0.7.26, pyloxone can no longer connect

### ISSUE THREAD

**Issue by ascha191** [JoDehli/PyLoxone#134]
Miniserver Gen1 
Version: 13.0.7.26
Hassio
Home Assistant 2022.10.4

After I updated the miniserver to 13.0.7.26, pyloxone can no longer connect

Log:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/loxone/__init__.py", line 156, in async_setup_entry
    if not await miniserver.async_setup():
  File "/config/custom_components/loxone/miniserver.py", line 118, in async_setup
    request_code = await self.lox_config.getJson()
  File "/config/custom_components/loxone/api.py", line 153, in getJson
    my_response = await client.get(LOXAPPPATH)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1751, in get
    return await self.request(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1527, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1614, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1642, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1700, in _send_handling_redirects
    raise exc
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
    await hook(response)
  File "/config/custom_components/loxone/api.py", line 84, in raise_if_not_200
    raise LoxoneHTTPStatusError(
custom_components.loxone.api.LoxoneHTTPStatusError: Miniserver response code 403

**Comment by JoDehli** [comment]
I have the same version. Try to login into the web GUI to loxone with the same user which you use in pyloxone.

**Comment by ascha191** [comment]
Thank you for your fast response but i have already found the problem. I also changed the password on my loxone server and forgot to update it on my node red instance. So my node red automations started an ddos attack on the miniserver.
