### ISSUE TITLE
Error message in log

### ISSUE THREAD

**Issue by noocyte** [JoDehli/PyLoxone#143]
**Which Model do you use from loxone? Miniserver Gen1**

**Which software version does your loxone use? 13.1**

**How did you install HomeAssistant? Hassio**

**Which Version do you use of HomeAssistant? 2022.11.3**

**Describe the bug**
Some entities are not working - switches does nothing. It appears that just after reboot they work, but after some time perhaps not... 

**Paste the error log with the following settings:**
```
Logger: custom_components.loxone
Source: custom_components/loxone/__init__.py:269
Integration: PyLoxone (documentation, issues)
First occurred: 20:17:03 (1 occurrences)
Last logged: 20:17:03

Can't create group 'Loxone Switches' with error: 'group_registry'
```

**Comment by JoDehli** [comment]
@noocyte I checked it on 2 machines and I can not reproduce the error. Which version pyloxone do you use? When did the error appear the first time? What did you change? I need more information.

**Comment by JoDehli** [comment]
@noocyte By coincidence, I now have the same error in my log. I have a log entry that looks like this: 

group: !include groups.yaml

When I comment it out, the error message comes up. Apparently something goes wrong with the group creation if this entry is not set. I'll take a look at it when I get a chance. Best at the moment just write this entry in the configuration.yaml.

**Comment by noocyte** [comment]
I'm sorry for being late responding. 

PyLoxone is version: 0.3.13

I did not have the groups.yaml file included in my configuration, I've added it in now. 

In my logs I'm getting this: 

```
Denne feilen stammer fra en tilpasset integrasjon.

Logger: homeassistant.config_entries
Source: custom_components/loxone/api.py:153
Integration: PyLoxone (documentation, issues)
First occurred: 13:41:47 (1 occurrences)
Last logged: 13:41:47

Error setting up entry PyLoxone for loxone
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection.py", line 90, in handle_async_request
    return await self._connection.handle_async_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 105, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 84, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 148, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 191, in _receive_event
    raise RemoteProtocolError(msg)
httpcore.RemoteProtocolError: Server disconnected without sending a response.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/loxone/__init__.py", line 156, in async_setup_entry
    if not await miniserver.async_setup():
  File "/config/custom_components/loxone/miniserver.py", line 118, in async_setup
    request_code = await self.lox_config.getJson()
  File "/config/custom_components/loxone/api.py", line 153, in getJson
    my_response = await client.get(LOXAPPPATH)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1751, in get
    return await self.request(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1527, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1614, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1642, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1679, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1716, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: Server disconnected without sending a response.

```

**Comment by JoDehli** [comment]
@noocyte please update first to the newest pyloxone.

**Comment by noocyte** [comment]
Looks like I was mistaken (aka. looked at the wrong thing) - I'm on 0.3.16 already

**Comment by noocyte** [comment]
I removed the `group: !include groups.yaml` line and reloaded the integration, now I have a new log entry (perhaps I try to 'push' a button).

``` 
Logger: homeassistant
Source: custom_components/loxone/api.py:387
Integration: PyLoxone (documentation, issues)
First occurred: 18:15:00 (1 occurrences)
Last logged: 18:15:00

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 979, in transfer_data
    await asyncio.shield(self._put_message_waiter)
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/loxone/miniserver.py", line 167, in listen_loxone_send
    await self.api.send_websocket_command(device_uuid, value)
  File "/config/custom_components/loxone/api.py", line 387, in send_websocket_command
    await self._ws.send(command)
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 944, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1011 (unexpected error) keepalive ping timeout; no close frame received
```

**Comment by JoDehli** [comment]
Can you include the groups entry and try the newest 0.4.0 (is a beta release).

**Comment by noocyte** [comment]
Initial tests are looking good! Loaded without any issues and a test automation I have worked as it should... So far so good! :)

**Comment by JoDehli** [comment]
Ok I put the service generation on top of the start this should it make it even more stable.

**Comment by noocyte** [comment]
Thank you so much! Not just for the support here, but for making and distributing PyLoxone! Much appreciated! :)
