### ISSUE TITLE
loxone.climate fails to load on 2023.1: cannot import name 'TEMP_CELSIUS' from 'homeassistant.components.climate'

### ISSUE THREAD

**Issue by Saviq** [JoDehli/PyLoxone#154]
**Which Model do you use from loxone? Miniserver? Gen1 or Gen2?**
Miniserver Go

**Which software version does your loxone use?**
13.1.11.17

**How did you install HomeAssistant? Over Hassio oder manual install?**
Hassio

**Which Version do you use of HomeAssistant?**
2023.1

**Describe the bug**
loxone.climate fails to load:

```
Unable to prepare setup for platform loxone.climate: Platform not found (cannot import name 'TEMP_CELSIUS' from 'homeassistant.components.climate' (/usr/src/homeassistant/homeassistant/components/climate/__init__.py)). 
```

**Paste the error log with the following settings:**
<details>
  <summary markdown="span">Debug logs</summary>
<pre>
2023-01-05 09:43:55.889 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-05 09:43:55.891 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration dyson_local which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-05 09:43:55.892 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration loxone which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-05 09:43:55.894 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-05 09:44:02.034 DEBUG (MainThread) [custom_components.loxone] starting loxone sensor...
2023-01-05 09:44:02.034 DEBUG (MainThread) [custom_components.loxone] starting loxone binary_sensor...
2023-01-05 09:44:02.034 DEBUG (MainThread) [custom_components.loxone] starting loxone switch...
2023-01-05 09:44:02.034 DEBUG (MainThread) [custom_components.loxone] starting loxone cover...
2023-01-05 09:44:02.034 DEBUG (MainThread) [custom_components.loxone] starting loxone light...
2023-01-05 09:44:02.034 DEBUG (MainThread) [custom_components.loxone] starting loxone climate...
2023-01-05 09:44:02.034 DEBUG (MainThread) [custom_components.loxone] starting loxone alarm_control_panel...
2023-01-05 09:44:02.126 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform loxone.climate: Platform not found (cannot import name 'TEMP_CELSIUS' from 'homeassistant.components.climate' (/usr/src/homeassistant/homeassistant/components/climate/__init__.py)).
2023-01-05 09:44:03.349 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform loxone.climate: Platform not found (cannot import name 'TEMP_CELSIUS' from 'homeassistant.components.climate' (/usr/src/homeassistant/homeassistant/components/climate/__init__.py)).
2023-01-05 09:44:03.351 DEBUG (MainThread) [custom_components.loxone.api] try to read token
2023-01-05 09:44:03.351 DEBUG (MainThread) [custom_components.loxone.api] try to get_token_from_file
2023-01-05 09:44:03.351 DEBUG (MainThread) [custom_components.loxone.api] try to get public key: http://loxone.michal.sawicz.net:8080/jdev/sys/getPublicKey
2023-01-05 09:44:03.958 DEBUG (MainThread) [custom_components.loxone.api] get_public_key successfully...
2023-01-05 09:44:04.000 DEBUG (MainThread) [custom_components.loxone.api] init_rsa_cipher successfully...
2023-01-05 09:44:04.006 DEBUG (MainThread) [custom_components.loxone.api] generate_session_key successfully...
2023-01-05 09:44:04.335 DEBUG (MainThread) [custom_components.loxone.api] parse_loxone_message successfully...
2023-01-05 09:44:04.335 DEBUG (MainThread) [custom_components.loxone.api] acquire_tokend
2023-01-05 09:44:04.337 DEBUG (MainThread) [custom_components.loxone.api] get_new_aes_chiper successfully...
2023-01-05 09:44:04.365 DEBUG (MainThread) [custom_components.loxone.api] parse_loxone_message successfully...
2023-01-05 09:44:04.366 DEBUG (MainThread) [custom_components.loxone.api] hash_credentials successfully...
2023-01-05 09:44:04.368 DEBUG (MainThread) [custom_components.loxone.api] get_new_aes_chiper successfully...
2023-01-05 09:44:04.468 DEBUG (MainThread) [custom_components.loxone.api] parse_loxone_message successfully...
2023-01-05 09:44:04.470 DEBUG (MainThread) [custom_components.loxone.api] save_token successfully...
2023-01-05 09:44:04.470 DEBUG (MainThread) [custom_components.loxone.api] get_new_aes_chiper successfully...
2023-01-05 09:44:04.483 DEBUG (MainThread) [custom_components.loxone] starting loxone scene...
2023-01-05 09:44:04.486 INFO (MainThread) [custom_components.loxone] loxone discovered
2023-01-05 09:44:10.904 DEBUG (MainThread) [custom_components.loxone.api] message [type:2]):{'15ae393b-0247-3471-ffff1aab58618af1': 6.0, '15ae393b-0263-3483-ffff1aab58618af1': 477.0, '15ae393b-0268-3486-ffff1aab58618af1': 955.0, '15ae393c-004c-373b-ffff8384a3d2cac7': 1.0, '1a56fb71-0037-05d1-ffff2a8592be3605': 0.0, '1a56fb69-0027-ff8f-ffffec087b3a64a1': 0.0, '1a56fb6c-0259-02ac-ffff6ff25faac66e': 0.0, '1a56fb67-0008-fc7a-fffffa960faee089': 0.0, '1a56c2b5-01e7-e782-ffff14d383581c34': 0.0, '1a56c2b5-01e7-e77c-ffff14d383581c34': 0.0, '1a56c2b4-031f-e47d-ffff5771e52e9122': 0.0, '1a56c2b4-031f-e477-ffff5771e52e9122': 0.0, '1a56c2b2-02ff-de9a-ffff65fe79a20d09': 0.0, '1a56c2b2-02ff-de94-ffff65fe79a20d09': 0.0, '1a56c2aa-013b-dba0-ffffa78e6046ada1': 0.0, '1a56c2aa-013b-db9a-ffffa78e6046ada1': 0.0, '1a56c04d-00a5-8322-ffff2b7a26889e5a': 0.0, '1a56c04d-00a5-831c-ffff2b7a26889e5a': 0.0, '1a56fb5f-03a2-f668-ffffd7c6039f81a8': 0.0, '1a56fb63-0382-f96d-ffff5436da037f94': 0.0, '1a56fb5a-0066-f36b-ffff7c99343f7bdb': 0.0, '1a56fb51-0382-ed89-ffffbedcdc429010': 0.0, '1a56fb57-0103-f076-ffff249783e38ca6': 0.0, '1a56fb4d-024a-eaa4-ffffb76ba8d3de87': 0.0, '1a56df79-0156-d707-ffffab5528ebe170': 0.0, '1a56df79-0156-d701-ffffab5528ebe170': 0.0, '1a56df78-0260-d457-ffff4ba672e3c56e': 0.0, '1a56df78-0260-d451-ffff4ba672e3c56e': 0.0, '1a56df77-039a-d1b4-ffff8e44d4b93a5c': 0.0, '1a56df77-039a-d1ae-ffff8e44d4b93a5c': 0.0, '1a56df77-002f-cf1e-ffff6190de120a94': 0.0, '1a56df77-002f-cf18-ffff6190de120a94': 0.0, '1a56df76-0176-cc95-ffffdcf18cdd7345': 0.0, '1a56df76-0176-cc8f-ffffdcf18cdd7345': 0.0, '1a56fb22-02d4-dc8a-ffff0903b4b5a568': 0.0, '1a56fb4b-0383-e7c7-fffff66062cda874': 0.0, '15ae393b-02c4-34bb-ffff1aab58618af1': 0.0, '15ae393b-02ca-34c4-ffff1aab58618af1': 441911964972.0}
2023-01-05 09:44:10.923 DEBUG (MainThread) [custom_components.loxone.api] message [type:3]):{'15ae393c-0087-3754-ffff8384a3d2cac7': '[]', '15ae393c-0087-3753-ffff8384a3d2cac7': '[]', '15ae393b-01cd-3441-ffff1aab58618af1': '[]', '15ae393b-01cd-3442-ffff1aab58618af1': '["hsv(25,96,50)","hsv(24,95,80)","hsv(337,94,50)"]', '15ae393b-01cd-3440-ffff1aab58618af1': '2023-01-05 09:44:06 +01:00:00', '1a569d9a-0270-5493-ffff1aab58618af1': '', '1a569d9a-0270-5494-ffff1aab58618af1': '{}', '1a569d9a-0270-5495-ffff1aab58618af1': '{}', '1a569d9a-0270-5496-ffff1aab58618af1': '{"cloudstatus":1,"services":[{"name":"caller","status":0},{"name":"weather","status":0},{"name":"registration","status":0}]}', '9a56fb71-0037-05ce-ffff2a8592be3605': '', '9a56fb69-0027-ff8c-ffffec087b3a64a1': '', '9a56fb6c-0259-02a9-ffff6ff25faac66e': '', '9a56fb67-0008-fc77-fffffa960faee089': '', '9a56c2b5-01e7-e77e-ffff14d383581c34': '', '9a56c2b4-031f-e479-ffff5771e52e9122': '', '9a56c2b2-02ff-de96-ffff65fe79a20d09': '', '9a56c2aa-013b-db9c-ffffa78e6046ada1': '', '9a56c04d-00a5-831e-ffff2b7a26889e5a': '', '9a56fb5f-03a2-f665-ffffd7c6039f81a8': '', '9a56fb63-0382-f96a-ffff5436da037f94': '', '9a56fb5a-0066-f368-ffff7c99343f7bdb': '', '9a56fb51-0382-ed86-ffffbedcdc429010': '', '9a56fb57-0103-f073-ffff249783e38ca6': '', '9a56fb4d-024a-eaa1-ffffb76ba8d3de87': '', '9a56df79-0156-d703-ffffab5528ebe170': '', '9a56df78-0260-d453-ffff4ba672e3c56e': '', '9a56df77-039a-d1b0-ffff8e44d4b93a5c': '', '9a56df77-002f-cf1a-ffff6190de120a94': '', '9a56df76-0176-cc91-ffffdcf18cdd7345': '', '9a56fb22-02d4-dc87-ffff0903b4b5a568': '', '9a56fb4b-0383-e7c4-fffff66062cda874': '', '15ae393b-02c4-34bc-ffff1aab58618af1': ''}
2023-01-05 09:44:10.931 DEBUG (MainThread) [custom_components.loxone.api] message [type:7]):{}
2023-01-05 09:44:13.926 WARNING (MainThread) [homeassistant.components.kodi.media_player] Unable to connect to Kodi via websocket
2023-01-05 09:44:15.167 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'latest_version' when rendering '{{ value_json['update']['latest_version'] }}'
2023-01-05 09:44:15.274 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'latest_version' when rendering '{{ value_json['update']['latest_version'] }}'
2023-01-05 09:44:15.392 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'latest_version' when rendering '{{ value_json['update']['latest_version'] }}'
2023-01-05 09:44:15.502 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'latest_version' when rendering '{{ value_json['update']['latest_version'] }}'
2023-01-05 09:44:15.516 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'latest_version' when rendering '{{ value_json['update']['latest_version'] }}'
2023-01-05 09:44:15.702 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'latest_version' when rendering '{{ value_json['update']['latest_version'] }}'
2023-01-05 09:44:15.816 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'latest_version' when rendering '{{ value_json['update']['latest_version'] }}'
2023-01-05 09:44:15.935 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'latest_version' when rendering '{{ value_json['update']['latest_version'] }}'
2023-01-05 09:44:17.571 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'latest_version' when rendering '{{ value_json['update']['latest_version'] }}'
2023-01-05 09:44:17.693 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'latest_version' when rendering '{{ value_json['update']['latest_version'] }}'
2023-01-05 09:44:17.739 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'latest_version' when rendering '{{ value_json['update']['latest_version'] }}'
2023-01-05 09:44:17.805 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'latest_version' when rendering '{{ value_json['update']['latest_version'] }}'
2023-01-05 09:44:17.855 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'latest_version' when rendering '{{ value_json['update']['latest_version'] }}'
2023-01-05 09:44:17.920 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'latest_version' when rendering '{{ value_json['update']['latest_version'] }}'
2023-01-05 09:44:18.082 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'latest_version' when rendering '{{ value_json['update']['latest_version'] }}'
2023-01-05 09:44:18.183 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'latest_version' when rendering '{{ value_json['update']['latest_version'] }}'
2023-01-05 09:44:24.209 DEBUG (MainThread) [custom_components.loxone.api] message [type:1]):{}
2023-01-05 09:44:43.027 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'latest_version' when rendering '{{ value_json['update']['latest_version'] }}'
2023-01-05 09:44:43.074 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'latest_version' when rendering '{{ value_json['update']['latest_version'] }}'
2023-01-05 09:44:43.091 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'latest_version' when rendering '{{ value_json['update']['latest_version'] }}'
2023-01-05 09:44:43.095 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'latest_version' when rendering '{{ value_json['update']['latest_version'] }}'
2023-01-05 09:44:43.099 ERROR (MainThread) [homeassistant.components.mqtt.select] Invalid option for select.ekran_backlight_mode: 'high' (valid options: ['LOW', 'MEDIUM', 'HIGH'])
2023-01-05 09:44:43.179 WARNING (MainThread) [homeassistant.components.automation.pralnia] Pralnia: Already running
2023-01-05 09:44:44.214 DEBUG (MainThread) [custom_components.loxone.api] message [type:1]):{}
2023-01-05 09:45:04.217 DEBUG (MainThread) [custom_components.loxone.api] message [type:1]):{}
2023-01-05 09:45:24.221 DEBUG (MainThread) [custom_components.loxone.api] message [type:1]):{}
</pre>
</details>

**Comment by elRadix** [comment]
same issue here, had to rollback the update December version. 
I have gen2 miniserver

**Comment by JoDehli** [comment]
@elRadix 
@Saviq 

fixed in 0.4.1

**Comment by elRadix** [comment]
still not resolved


```
Logger: homeassistant.components.climate
Source: custom_components/loxone/climate.py:223
Integration: Climate (documentation, issues)
First occurred: 10:49:33 (2 occurrences)
Last logged: 10:49:33

Error adding entities for domain climate with platform loxone
Error while setting up loxone platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 438, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 621, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 264, in capability_attributes
    self.hass, self.min_temp, self.temperature_unit, self.precision
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 564, in min_temp
    DEFAULT_MIN_TEMP, UnitOfTemperature.CELSIUS, self.temperature_unit
  File "/config/custom_components/loxone/climate.py", line 223, in temperature_unit
    return  UnitOfTemperature.TEMP_CELSIUS
  File "/usr/local/lib/python3.10/enum.py", line 437, in __getattr__
    raise AttributeError(name) from None
AttributeError: TEMP_CELSIUS

```

**Comment by shvnrg** [comment]
> still not resolved
> 
> ```
> Logger: homeassistant.components.climate
> Source: custom_components/loxone/climate.py:223
> Integration: Climate (documentation, issues)
> First occurred: 10:49:33 (2 occurrences)
> Last logged: 10:49:33
> 
> Error adding entities for domain climate with platform loxone
> Error while setting up loxone platform for climate
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 438, in async_add_entities
>     await asyncio.gather(*tasks)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 621, in _async_add_entity
>     capabilities=entity.capability_attributes,
>   File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 264, in capability_attributes
>     self.hass, self.min_temp, self.temperature_unit, self.precision
>   File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 564, in min_temp
>     DEFAULT_MIN_TEMP, UnitOfTemperature.CELSIUS, self.temperature_unit
>   File "/config/custom_components/loxone/climate.py", line 223, in temperature_unit
>     return  UnitOfTemperature.TEMP_CELSIUS
>   File "/usr/local/lib/python3.10/enum.py", line 437, in __getattr__
>     raise AttributeError(name) from None
> AttributeError: TEMP_CELSIUS
> ```

Can confirm, Same error log for me after updating.

**Comment by JoDehli** [comment]
@Saviq and @elRadix had a little error. Noticed right after I messed you. Pleas download the 0.4.1 again.

**Comment by shvnrg** [comment]
@JoDehli working, thanks a lot for the support

**Comment by elRadix** [comment]
it's fixed now?!

Thank you @JoDehli!!

**Comment by rosch99** [comment]
had the same error after upgrading to 2023.1
0.4.1 fixed the problem. :-)
Thanks @JoDehli for the ultrafast support and update!
