### ISSUE TITLE
Websocket connections unexpectedly closed.

### ISSUE THREAD

**Issue by johny-mnemonic** [JoDehli/PyLoxone#155]
**Which Model do you use from loxone? Miniserver? Gen1 or Gen2?**
Gen1
**Which software version does your loxone use?**
13.1.11.17
**How did you install HomeAssistant? Over Hassio oder manual install?**
Official OVA image with Hassio
**Which Version do you use of HomeAssistant?**
Home Assistant 2023.1.0
Supervisor 2022.12.1
Operating System 9.3
Frontend 20230104.0 - latest

**Describe the bug**
I am randomly getting following errors while trying to set a value in Loxone from HA automation using websocket service call.

```
Logger: homeassistant.components.automation.loxone_set_solax_grid_power
Source: custom_components/loxone/api.py:386
Integration: Automatizace ([documentation](https://www.home-assistant.io/integrations/automation), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+automation%22))
First occurred: 15:20:31 (42 occurrences)
Last logged: 15:24:32

Loxone - Set Solax Grid power: Error executing script. Unexpected error for call_service at pos 1: received 1000 (OK) normally closed; then sent 1000 (OK) normally closed
While executing automation automation.loxone_set_solax_grid_power
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1755, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1792, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/loxone/__init__.py", line 238, in handle_websocket_command
    await miniserver.api.send_websocket_command(device_uuid, value)
  File "/config/custom_components/loxone/api.py", line 386, in send_websocket_command
    await self._ws.send(command)
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 944, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK) normally closed; then sent 1000 (OK) normally closed
```

The automation looks like this:
```
alias: Loxone - Set Solax Grid power
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.solax_measured_power
condition: []
action:
  - service: loxone.event_websocket_command
    data:
      uuid: XXXXXXXXXXXXXXXXXXXXXXXXXX
      value: "{{states.sensor.solax_measured_power.state | float * -0.001}}"
mode: single
```

The sensor `sensor.solax_measured_power` is updated every 10s, so it should not be overloading the Loxone Miniserver, but I admin the error generally looks like the Miniserver is refusing the communication🤷‍♂️
Also the HA log says 42 occurences in 4 minutes which doesn't match 10s frequency of updates. Are there any retries in PyLoxone?
Any advice in which direction to try to dig deeper?

**Comment by JoDehli** [comment]
@johny-mnemonic Have you tried it manually with a service call from the gui (webbrowser)? 
Has the value a space in it. Because the value and uuid is connected to one command and if there is a space it will fail. But I think you can try it by hand with the gui and service.

**Comment by johny-mnemonic** [comment]
@JoDehli maybe it was not clear from my description, but it works daily in thousands of calls. It is updating the reading from an electric meter every 10 seconds from HA to Loxone.
But sometimes it throws this error. Usually it throws few of these and then it works again, but few times it basically stopped working and I had to restart HA to make it working again.
I don't think it is possible to have a space in the value from the meter it's just a float value that can also be negative. I will try to catch the trace from the automation though or add debug logging to PyLoxone to see what value it is sending.

**Comment by JoDehli** [comment]
@johny-mnemonic OK could be that the value is something wrong or none from the source. Or as the sending and receiving makes sometimes problems. In the first place it was not implemented that you sent so many values in such a short time. I am working an a complete rewrite of the communication. I hope I can implement it without bigger problems in the next month. There are some other improvements like a reload without restarting home assistant completely. I worked together with a other pyloxone programmer over Christmas. When you still have this problem with the new implementation we could dig deeper for the problem.

**Comment by johny-mnemonic** [comment]
@JoDehli yeah, I was suspecting I might be overloading either PyLoxone or the Miniserver itself.
As a backup I might be able to configure Loxone to read the electric meter values directly using Modbus TCP. It was just easier to use HA integration instead :-)
Thanks for help and good luck with the rewrite!

**Comment by johny-mnemonic** [comment]
Not sure whether it would be of any use, but here is current occurrence and reloading PyLoxone is not helping.
Looking at the current error and the one in OP I am afraid I have copied wrong one in the OP. That one looks like from the time Miniserver was reloading due to new config. This one is the one that happens randomly.
```
Logger: homeassistant.components.automation.loxone_set_solax_grid_power
Source: custom_components/loxone/api.py:386
Integration: Automatizace ([documentation](https://www.home-assistant.io/integrations/automation), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+automation%22))
First occurred: 19:53:05 (556 occurrences)
Last logged: 20:40:55

Loxone - Set Solax Grid power: Error executing script. Unexpected error for call_service at pos 1: sent 1011 (unexpected error) keepalive ping timeout; no close frame received
While executing automation automation.loxone_set_solax_grid_power
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 979, in transfer_data
    await asyncio.shield(self._put_message_waiter)
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1755, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1792, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/loxone/__init__.py", line 238, in handle_websocket_command
    await miniserver.api.send_websocket_command(device_uuid, value)
  File "/config/custom_components/loxone/api.py", line 386, in send_websocket_command
    await self._ws.send(command)
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 944, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1011 (unexpected error) keepalive ping timeout; no close frame received
```

**Comment by JoDehli** [comment]
@johny-mnemonic you mean restarting not reloading. Reloading is not supported at the moment. Only restarting of Homeassistent restarts the connection to loxone. 

There is something wrong with the websocket send command. Maybe it is a strange value from the source.

**Comment by JoDehli** [comment]
@johny-mnemonic you mean restarting not reloading. Reloading is not supported at the moment. Only restarting of Homeassistent restarts the connection to loxone. 

There is something wrong with the websocket send command. Maybe it is a strange value from the source. 

For sending the same time normally we should put the message in a queue and send them all one by one. But as I said I was not implemented for such a task. 


Can you make a automation for each sensor with different delays? For example send the first value after 0.5 seconds and the next after 1 second and so on.

**Comment by johny-mnemonic** [comment]
I tried reloading as I didn't know it's not supposed to work so it's clear why it didn't do anything :-)

Adding delays is good idea. Thanks!
I have five values from PV inverter and three of them are electric meters (changing fast) so I have added delays for all five of these to spread them out each 0.5s after another. Let's see whether it will make any difference.

**Comment by johny-mnemonic** [comment]
@JoDehli So far it looks much better with different delays, so it really look like the issues were caused by multiple websocket calls at the same time.
BTW: When you are rewriting this part of the integration, would it make sense to make it smarter and detect whether the Miniserver is reloading/restarting? 
Web app and mobile app both tell you this info when Miniserver is reloading/restarting, so there must be a way to detect it. It would be better to either buffer the calls or gracefully gave up rather than failing for 1-3 minutes and filling the log of HA with stack traces...

**Comment by JoDehli** [comment]
@johny-mnemonic yes that are good improvements. We try to implement it.
