### ISSUE TITLE
Error setting up entry PyLoxone for loxone (can anyone help?)

### ISSUE THREAD

**Issue by Car1it0** [JoDehli/PyLoxone#156]
Gen 2 
Loxone 13.1
Home Assistant using HAC

Logger: homeassistant.config_entries
Source: custom_components/loxone/api.py:84
Integration: PyLoxone ([documentation](https://github.com/JoDehli/PyLoxone), [issues](https://github.com/JoDehli/PyLoxone/issues))
First occurred: 10:21:37 (3 occurrences)
Last logged: 10:27:07

Error setting up entry PyLoxone for loxone
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/loxone/__init__.py", line 195, in async_setup_entry
    if not await miniserver.async_setup():
  File "/config/custom_components/loxone/miniserver.py", line 140, in async_setup
    request_code = await self.lox_config.getJson()
  File "/config/custom_components/loxone/api.py", line 122, in getJson
    api_resp = await client.get("/jdev/cfg/apiKey")
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1757, in get
    return await self.request(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1533, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1620, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1648, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1706, in _send_handling_redirects
    raise exc
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1688, in _send_handling_redirects
    await hook(response)
  File "/config/custom_components/loxone/api.py", line 84, in raise_if_not_200
    raise LoxoneHTTPStatusError(
custom_components.loxone.api.LoxoneHTTPStatusError: Miniserver response code 307
```

**Comment by Car1it0** [comment]
2023-01-06 10:27:07.007 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry PyLoxone for loxone
File "/config/custom_components/loxone/__init__.py", line 195, in async_setup_entry
File "/config/custom_components/loxone/miniserver.py", line 140, in async_setup
File "/config/custom_components/loxone/api.py", line 122, in getJson
File "/config/custom_components/loxone/api.py", line 84, in raise_if_not_200
raise LoxoneHTTPStatusError(
custom_components.loxone.api.LoxoneHTTPStatusError: Miniserver response code 307

**Comment by JoDehli** [comment]
I think you have gen2. Please try the local IP address an port. I am currently working on a new implement which should work better with the gen 2

**Comment by Car1it0** [comment]
Ok i was using the LxoneDNS, simply using local IP solved (might want to update your instructions) and BTW i prefer using IP vs loxoneDNS>

Thx for all the effort
