### ISSUE TITLE
No events coming from Loxone all of a sudden `ConnectionClosedError: sent 1011`

### ISSUE THREAD

**Issue by Saviq** [JoDehli/PyLoxone#162]
**Which Model do you use from loxone? Miniserver? Gen1 or Gen2?**
Miniserver Go

**Which software version does your loxone use?**
13.1.11.17

**How did you install HomeAssistant? Over Hassio oder manual install?**
Hassio

**Which Version do you use of HomeAssistant?**
Home Assistant 2023.1.7
Supervisor 2023.01.1
Operating System 9.5
User interface: 20230110.0 - latest 

**Describe the bug**
No events are coming through suddenly. Entities are synchronized fine, but nothing happens beyond that. It was all working fine until yesterday. Looks like the websocket connection is interrupted. May be similar to #155.

**Paste the error log with the following settings:**
```
Logger: homeassistant
Source: custom_components/loxone/api.py:386
Integration: PyLoxone ([documentation](https://github.com/JoDehli/PyLoxone), [issues](https://github.com/JoDehli/PyLoxone/issues))
First occurred: 13:37:49 (54 occurrences)
Last logged: 13:37:57
Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 979, in transfer_data
    await asyncio.shield(self._put_message_waiter)
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/loxone/miniserver.py", line 189, in listen_loxone_send
    await self.api.send_websocket_command(device_uuid, value)
  File "/config/custom_components/loxone/api.py", line 386, in send_websocket_command
    await self._ws.send(command)
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 944, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1011 (unexpected error) keepalive ping timeout; no close frame received
```

**Comment by JoDehli** [comment]
What did you change yesterday? New ha version?

**Comment by Saviq** [comment]
@JoDehli no, my last upgrade was a week ago, the uptime on the system is longer than the problem. Restarting HA a couple times brought it back.

**Comment by JoDehli** [comment]
That means brought it back the error or brought the system back to work?

**Comment by Saviq** [comment]
Sorry, brought it back to work. It's fine now, and the error above isn't in the current run's logs.

**Comment by JoDehli** [comment]
Ok then I close the issue. If it happen again you can reopen it.
