### ISSUE TITLE
Beta 0.5.0b4 crashing HomeAssistant

### ISSUE THREAD

**Issue by johny-mnemonic** [JoDehli/PyLoxone#173]
Miniserver: Gen1
Loxone: 13.1.11.17
Hassio OS 9.5
HomeAssistant: 2023.3.6

After updating from 0.5.0b3 to 0.5.0b4 and restarting HA it failed to start with lot of PyLoxone related stack traces in the log.

```
Mar 27 06:03:44 homeassistant homeassistant[773815]: 2023-03-27 08:03:44.156 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry PyLoxone for binary_sensor
Mar 27 06:03:44 homeassistant homeassistant[773815]: Traceback (most recent call last):
Mar 27 06:03:44 homeassistant homeassistant[773815]:   File "/config/custom_components/loxone/__init__.py", line 643, in __init__
Mar 27 06:03:44 homeassistant homeassistant[773815]:     setattr(self, key, kwargs[key])
Mar 27 06:03:44 homeassistant homeassistant[773815]: AttributeError: can't set attribute 'device_class'
Mar 27 06:03:44 homeassistant homeassistant[773815]:
Mar 27 06:03:44 homeassistant homeassistant[773815]: During handling of the above exception, another exception occurred:
Mar 27 06:03:44 homeassistant homeassistant[773815]:
Mar 27 06:03:44 homeassistant homeassistant[773815]: Traceback (most recent call last):
Mar 27 06:03:44 homeassistant homeassistant[773815]:   File "/usr/src/homeassistant/homeassistant/runner.py", line 179, in run
Mar 27 06:03:44 homeassistant homeassistant[773815]:     return loop.run_until_complete(setup_and_run_hass(runtime_config))
Mar 27 06:03:44 homeassistant homeassistant[773815]:   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
Mar 27 06:03:44 homeassistant homeassistant[773815]:     self.run_forever()
Mar 27 06:03:44 homeassistant homeassistant[773815]:   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
Mar 27 06:03:44 homeassistant homeassistant[773815]:     self._run_once()
Mar 27 06:03:44 homeassistant homeassistant[773815]:   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
Mar 27 06:03:44 homeassistant homeassistant[773815]:     handle._run()
Mar 27 06:03:44 homeassistant homeassistant[773815]:   File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
Mar 27 06:03:44 homeassistant homeassistant[773815]:     self._context.run(self._callback, *self._args)
Mar 27 06:03:44 homeassistant homeassistant[773815]:   File "/config/custom_components/loxone/fan.py", line 96, in async_setup_entry
Mar 27 06:03:44 homeassistant homeassistant[773815]:     entites.append(Loxonesensor(**humidity))
Mar 27 06:03:44 homeassistant homeassistant[773815]:   File "/config/custom_components/loxone/sensor.py", line 359, in __init__
Mar 27 06:03:44 homeassistant homeassistant[773815]:     LoxoneEntity.__init__(self, **kwargs)
Mar 27 06:03:44 homeassistant homeassistant[773815]:   File "/config/custom_components/loxone/__init__.py", line 646, in __init__
Mar 27 06:03:44 homeassistant homeassistant[773815]:     sys.exit(-1)
Mar 27 06:03:44 homeassistant homeassistant[773815]: SystemExit: -1
Mar 27 06:03:44 homeassistant homeassistant[773815]:
Mar 27 06:03:44 homeassistant homeassistant[773815]: During handling of the above exception, another exception occurred:
Mar 27 06:03:44 homeassistant homeassistant[773815]:
Mar 27 06:03:44 homeassistant homeassistant[773815]: Traceback (most recent call last):
Mar 27 06:03:44 homeassistant homeassistant[773815]:   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
Mar 27 06:03:44 homeassistant homeassistant[773815]:     result = await component.async_setup_entry(hass, self)
Mar 27 06:03:44 homeassistant homeassistant[773815]:   File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 169, in async_setup_entry
Mar 27 06:03:44 homeassistant homeassistant[773815]:     return await component.async_setup_entry(entry)
Mar 27 06:03:44 homeassistant homeassistant[773815]:   File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 174, in async_setup_entry
Mar 27 06:03:44 homeassistant homeassistant[773815]:     return await self._platforms[key].async_setup_entry(config_entry)
Mar 27 06:03:44 homeassistant homeassistant[773815]:   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 265, in async_setup_entry
Mar 27 06:03:44 homeassistant homeassistant[773815]:     return await self._async_setup_platform(async_create_setup_task)
Mar 27 06:03:44 homeassistant homeassistant[773815]:   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
Mar 27 06:03:44 homeassistant homeassistant[773815]:     await asyncio.shield(task)
Mar 27 06:03:44 homeassistant homeassistant[773815]: asyncio.exceptions.CancelledError
```
Seems like it generates such error for each and every device class PyLoxone is trying to setup in HA and as it ends with `SystemExit: -1` it breaks HA startup.

**Comment by JoDehli** [comment]
@johny-mnemonic I catchend the error. Maybe you have custom sensors where you have not defined a device class.

**Comment by johny-mnemonic** [comment]
@JoDehli any possibility it is related to me trying the testing branch [here](https://github.com/JoDehli/PyLoxone/issues/164)?
I am not aware of having custom device class defined on Loxone entities but I could be wrong. Before I reported #164 I had it defined in `customize.yaml` for two energy sensors, but I have removed it since.

**Comment by JoDehli** [comment]
@johny-mnemonic I suppressed the error message but the missing device class is still present. So I do not know what is different on you system then on other systems. I can not reproduce it. On my system I can set the device class.

Can you setup a second home assistant instance with and try to connect to your loxone and see if the errors still exists. Maybe with a empty database the errors  do not occur.

**Comment by johny-mnemonic** [comment]
Can I try 0.5.0b5? Would it tell us which entities are the source of the trouble?

**Comment by JoDehli** [comment]
@johny-mnemonic yes in the log file you should see a info that it could not set the device class. 

And it you try it with a new installation with clean database it would be interesting if the logs are not present anymore. 

It has to do specific with you machine. Because I do not get this errors.

**Comment by johny-mnemonic** [comment]
@JoDehli I have updated to 0.5.0b5 and I have zero errors in the log 🤯 
Should I try to restart with debug enabled?

**Comment by JoDehli** [comment]
@johny-mnemonic I said info not errors. I catches the error and printed a info message. So by setting the log level right you will see the messages
