### ISSUE TITLE
"Error adding entities for domain cover with platform loxone" since 2023.8

### ISSUE THREAD

**Issue by bartn80** [JoDehli/PyLoxone#189]
**Which Model do you use from loxone? Miniserver? Gen1 or Gen2?**
Gen2

**Which software version does your loxone use?**
14.2.6.16

**How did you install HomeAssistant? Over Hassio or manual install?**
HACS

**Which Version do you use of HomeAssistant?**
2023.8

**Describe the bug**
2023-08-03 18:32:07.680 ERROR (MainThread) [homeassistant.components.cover] Error adding entities for domain cover with platform loxone
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'type'
2023-08-03 18:32:07.704 ERROR (MainThread) [homeassistant.components.cover] Error while setting up loxone platform for cover
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 370, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'type'

**Comment by JoDehli** [comment]
@bartn80 update to the newest release of pyloxone. I pushed a release a few minutes ago.

**Comment by bartn80** [comment]
Everything is working again, thanks!
