### ISSUE TITLE
Integration not working

### ISSUE THREAD

**Issue by I-am-OK-86** [JoDehli/PyLoxone#191]
**Which Model do you use from loxone? Miniserver? Gen1 or Gen2?** Gen2

**Which software version does your loxone use?** 14.2.6.16

**How did you install HomeAssistant? Over Hassio or manual install?** Hasso

**Which Version do you use of HomeAssistant?** 2023.8.1

**Describe the bug**
Error while installing. No devices or entities found. I updated PyLoxone but this did not helped. Then I deleted the whole installation, restarted HA completely and installed it once again. Still the same error.

**Paste the error log with the following settings:**

Logger: homeassistant.helpers.integration_platform
Source: loader.py:850 
First occurred: 12:09:24 (8 occurrences) 
Last logged: 12:09:53

Unexpected error importing loxone/logbook.py
Unexpected error importing loxone/media_source.py
Unexpected error importing loxone/cast.py
Unexpected error importing loxone/significant_change.py
Unexpected error importing loxone/hardware.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 50, in _async_process_single_integration_platform_component
    platform = integration.get_platform(platform_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 833, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 850, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.Loxone.diagnostics'

**Comment by JoDehli** [comment]
Which custom components have you installed other then pyloxone?

**Comment by I-am-OK-86** [comment]
None custom components other the PyLoxone. I have the following major standard integrations installed in HA:
- NodeRed
- Overkiz
Further, there are some smaller ones which have been automatically identified in my network like Fritz, Nuki, Synology, Philips, Android and a couple other minor integrations.

**Comment by JoDehli** [comment]
I really have no clue what is going on your system sorry. Never had such issues. Must think about what we can do?

**Comment by I-am-OK-86** [comment]
I forgot to mention that I also have HACS as custom integration.

**Comment by I-am-OK-86** [comment]
I have now tried back and forth and a least when typing in the local IP address to the config instead of loxonecloud I was able to reload some entities and devices. However, the list is not complete - many of them are missing which were there befor the error occurred and I deleted the whole installation. Further, the error message still appears.

**Comment by JoDehli** [comment]
@I-am-OK-86  when was your last loxone miniserver update?

**Comment by I-am-OK-86** [comment]
Today. This was one of the first steps I did when I noticed the issue.

**Comment by JoDehli** [comment]
@I-am-OK-86 have you tried the beta of pyloxone?


And you must use the local IP address. 

As I do not have a gen2 I can not really test it what changed. In the future I will only support gen1.

**Comment by I-am-OK-86** [comment]
Yes but I can try again. And yes, I also used the local IP address. Which ports do you recommend?

**Comment by JoDehli** [comment]
@I-am-OK-86 not Port 80

**Comment by I-am-OK-86** [comment]
Tried another one with Beta version but still the same issue.

**Comment by JoDehli** [comment]
@I-am-OK-86 did it ever work? Or did you have that problem from the beginning.

**Comment by I-am-OK-86** [comment]
I worked very well until the last HA update.

**Comment by JoDehli** [comment]
@I-am-OK-86 can install home assistant on a different machine. Maybe a laptop or pc and try it there. 

If you familiar with python you can create a virtual environment and thee you can install different versions of home assistant. It would be interesting if it will work with a previous version.

**Comment by JoDehli** [comment]
@I-am-OK-86 did you made any progress?

**Comment by I-am-OK-86** [comment]
I will try it today and update the ticket then.

**Comment by I-am-OK-86** [comment]
I tested another HA installation on a VM and there everything worked well. Thus, I deleted my installation and installed everything again using a backup. Now it works. So it was no error on PyLoxone side but something really strange in my HA installation.
