### ISSUE TITLE
Could not connect to Loxone

### ISSUE THREAD

**Issue by fl1p1** [JoDehli/PyLoxone#198]
**Which Model do you use from loxone? Miniserver? Gen1 or Gen2?**
Gen 2

**Which software version does your loxone use?**
14.3.8.3

**How did you install HomeAssistant? Over Hassio or manual install?**
Manual

**Which Version do you use of HomeAssistant?**
Home Assistant 2023.8.3
Supervisor 2023.08.1
Operating System 10.5
Frontend-versie: 20230802.1 - latest

**Describe the bug**
Could nog connect to Loxone Climate sensors (and none of the sensors in addition.
It has been like this for a few versions of HA, but I thought maybe an update would fix it.

**Paste the error log:**
```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:619
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 09:30:41 (2 occurrences)
Last logged: 09:30:42

Error adding entities for domain sensor with platform loxone
Error while setting up loxone platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'type'
```

```
Logger: homeassistant.components.cover
Source: helpers/entity_platform.py:619
Integration: Afdekkingen ([documentation](https://www.home-assistant.io/integrations/cover), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+cover%22))
First occurred: 09:30:42 (2 occurrences)
Last logged: 09:30:42

Error adding entities for domain cover with platform loxone
Error while setting up loxone platform for cover
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'type'
```

**Comment by JoDehli** [comment]
@fl1p1 did you update pyloxone? I can not reproduce this error at all.

**Comment by JoDehli** [comment]
@fl1p1 the last version of pyloxone had some issues because of a change in homeassistant. But the newest pyloxone should work with the latest homeassistant.

**Comment by fl1p1** [comment]
Silly me... I thought this would be also updated automatically. Thanks for opening my eyes! Works fine now.
