### ISSUE TITLE
Detected I/O inside the event loop

### ISSUE THREAD

**Issue by geertsmichael** [JoDehli/PyLoxone#21]
Since Home assistant 0.109.0 they build in a check for too much I/O operations (or http calls).

I am seeing this in my log files:

2020-05-02 21:57:09 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for loxone doing I/O at custom_components/loxone/__init__.py, line 112: verify=False)

2020-05-02 21:57:10 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for loxone doing I/O at custom_components/loxone/__init__.py, line 992: response = requests.get(command, auth=(self._username, self._pasword), timeout=1)

It's related to this:
https://www.home-assistant.io/blog/2020/04/29/release-109/#detection-of-blocking-io-in-the-event-loop

I cannot understand python well, but could it be that the same http call is performed multiple times?

Could you have a look at this problem.

It's causing me to restart Home assistant 10 times and 9 out of 10 cases, Loxone fails to startup.

**Comment by geertsmichael** [comment]
I also want to add that the scenes are not generated anymore for me.
I am running Loxone 11 and Home assistant 0.109.2

**Comment by JoDehli** [comment]
Please try the dev branch. But I think the restarts are not from this message. My installation reported the same error but still worked as expected. I was not a big performance issue. There are only 3 requests which were not async. All the other requests were already async.

**Comment by geertsmichael** [comment]
With the restarts I meant that I manually restart home assistant after writing new config, but to apply that config I restart my HA.
When HA starts up again, 9 out of 10 times it didn't start up Loxone for me.
These scenes are always missing.

I will try the dev branch.

**Comment by geertsmichael** [comment]
No difference with the dev branch.

I had the issue gain today after a restart. After. closer look at the log files, I see this:

2020-05-03 17:42:23 ERROR (MainThread) [homeassistant.setup] Error during setup of component loxone
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/websockets/http.py", line 139, in read_response
    status_line = await read_line(stream)
  File "/usr/local/lib/python3.7/site-packages/websockets/http.py", line 219, in read_line
    raise EOFError("line without CRLF")
EOFError: line without CRLF

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/websockets/client.py", line 101, in read_http_response
    status_code, reason, headers = await read_response(self.reader)
  File "/usr/local/lib/python3.7/site-packages/websockets/http.py", line 141, in read_response
    raise EOFError("connection closed while reading HTTP status line") from exc
EOFError: connection closed while reading HTTP status line

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 171, in _async_setup_component
    hass, processed_config
  File "/config/custom_components/loxone/__init__.py", line 309, in async_setup
    res = await lox.async_init()
  File "/config/custom_components/loxone/__init__.py", line 600, in async_init
    timeout=TIMEOUT)
  File "/usr/local/lib/python3.7/site-packages/websockets/client.py", line 547, in __await_impl__
    extra_headers=protocol.extra_headers,
  File "/usr/local/lib/python3.7/site-packages/websockets/client.py", line 290, in handshake
    status_code, response_headers = await self.read_http_response()
  File "/usr/local/lib/python3.7/site-packages/websockets/client.py", line 103, in read_http_response
    raise InvalidMessage("did not receive a valid HTTP response") from exc
websockets.exceptions.InvalidMessage: did not receive a valid HTTP response


2020-05-03 17:42:25 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform loxone.scene: Unable to set up component.
2020-05-03 17:42:27 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform loxone.switch: Unable to set up component.
2020-05-03 17:42:27 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform loxone.cover: Unable to set up component.
2020-05-03 17:42:29 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform loxone.light: Unable to set up component.
2020-05-03 17:42:32 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform loxone.alarm_control_panel: Unable to set up component.
2020-05-03 17:42:46 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform loxone.sensor: Unable to set up component.

**Comment by JoDehli** [comment]
Please try the dev branch. You have the old sources. Or at least the logs are from a old source as I can see for example at this log line: 
File "/config/custom_components/loxone/init.py", line 309, in async_setup
res = await lox.async_init()

In the dev branch (not Master) the res = await lox.async_init() line is not in 309. 
In the dev brach it should be 323. 

But there are also errors which are strange. Like this one: 

File "/usr/local/lib/python3.7/site-packages/websockets/client.py", line 103, in read_http_response
raise InvalidMessage("did not receive a valid HTTP response") from exc

Normally you get a message like this if the Miniserver refuses your request. This happens when you tried it to often with wrong password or something happened during connection.

**Comment by vicfalls** [comment]
I have the sam log try like @geertsmichael.

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for loxone doing I/O at custom_components/loxone/__init__.py, line 112: verify=False)
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for loxone doing I/O at custom_components/loxone/__init__.py, line 992: response = requests.get(command, auth=(self._username, self._pasword), timeout=1)

Loxone connection works fine so far....

**Comment by JoDehli** [comment]
@vicfalls did you try the dev branch. I already fixed the binding in the dev branch. I will merge it into the mein branch soon.

**Comment by JoDehli** [comment]
@geertsmichael I updated to the newest loxone firmware and the binding is still working with no errors.

**Comment by vicfalls** [comment]
@JoDehli , I tried it with dev branch, same result. I have the old FW on my Miniserver.

**Comment by vicfalls** [comment]
> @JoDehli , I tried it with dev branch, same result. I have the old FW on my Miniserver.

@JoDehli, my information was wrong. I installed the dev branch and all the error massages are gone now. Thanks Dev
