### ISSUE TITLE
[Bug]: Inteligent Room Controller not working after update

### ISSUE THREAD

**Issue by zach-ovic** [JoDehli/PyLoxone#255]
### Describe the bug

After updating Loxone Miniserver and PyLoxon all Inteligent Room Controllers (climate platform) entities are now unavailable.

### Firmware of your Miniserver

14.7.3.6

### HomeAssistant install method

Home Assistant OS

### Version of HomeAssistant

Home Assistant Core Installed 2024.1.6
Home Assistant Operating System 11.4

### Version of Pyloxone

0.6.3

### Update pyloxone

Yes

### Log

[home-assistant.log](https://github.com/JoDehli/PyLoxone/files/14735847/home-assistant.log)

**Comment by zach-ovic** [comment]
I guess this could be the problem:

```
2024-03-24 15:56:06.711 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.loxone.climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/loxone/climate.py", line 108, in <module>
    class LoxoneRoomControllerV2(LoxoneEntity, ClimateEntity, ABC):
  File "/config/custom_components/loxone/climate.py", line 114, in LoxoneRoomControllerV2
    | ClimateEntityFeature.TURN_OFF
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 784, in __getattr__
    raise AttributeError(name) from None
AttributeError: TURN_OFF
2024-03-24 15:56:06.733 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform 'loxone.climate': Platform not found (Exception importing custom_components.loxone.climate).
2024-03-24 15:56:06.755 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.loxone.climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by JoDehli** [comment]
@zach-ovic you need the newest home assistant. please update.

**Comment by zach-ovic** [comment]
Ok. I see that now. It's a missing enum value. 

Isn't it the manifest.json for this? Shouldn't it be updated in the repo? Not trying to complain, I understand that maintaining this is a lot of work.
