### ISSUE TITLE
[Bug]: Pushbutton does not work after upgrade to Core 2024.5.0

### ISSUE THREAD

**Issue by rolandpj** [JoDehli/PyLoxone#266]
### Describe the bug

When I trigger a "Pushbutton" HA reports this error:
RuntimeError: Detected that custom integration 'loxone' calls async_fire from a thread at custom_components/loxone/switch.py, line 253: self.hass.bus.async_fire(. Please report it to the author of the 'loxone' custom integration.

occurs since I installed Core 2024.5.0 yesterday.

### Firmware of your Miniserver

14.7.3.6

### HomeAssistant install method

Hassio

### Version of HomeAssistant

Core 2024.5.0
Supervisor 2024.04.4
Operating System 12.2
Frontend 20240501.0

### Version of Pyloxone

0.6.4

### Update pyloxone

yes

### Log

Logger: homeassistant.components.websocket_api.http.connection
Quelle: components/websocket_api/commands.py:239
Integration: Home Assistant WebSocket API (Dokumentation, Probleme)
Erstmals aufgetreten: 00:50:07 (12 Vorkommnisse)
Zuletzt protokolliert: 08:14:30

[547247323072] Unexpected exception
[546926909504] Unexpected exception
[546784492224] Unexpected exception
[546965996864] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2738, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2779, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1047, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1680, in async_turn_on
    await self.hass.async_add_executor_job(ft.partial(self.turn_on, **kwargs))
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/loxone/switch.py", line 253, in turn_on
    self.hass.bus.async_fire(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1508, in async_fire
    self._hass.verify_event_loop_thread("async_fire")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'loxone' calls async_fire from a thread at custom_components/loxone/switch.py, line 253: self.hass.bus.async_fire(. Please report it to the author of the 'loxone' custom integration.

**Comment by JoDehli** [comment]
@rolandpj at the moment it is not compatible with the the newest HA . Please downgrade.
