### ISSUE TITLE
"Error during setup of component loxone"

### ISSUE THREAD

**Issue by Saviq** [JoDehli/PyLoxone#30]
Hi,

I can't seem to hook up to a Miniserver Go. I can confirm it's working over HTTP (port 80), but I can't get HA to connect to it.

My config (I also tried `port: 80`, but that didn't change anything):
```yaml
loxone:
  port: 8080
  host: 10.2.0.48
  username: admin
  password: admin
  generate_scenes: false
```

The error:
```pytb
2020-07-11 23:23:29 WARNING (MainThread) [homeassistant.setup] Setup of loxone is taking over 10 seconds.
2020-07-11 23:23:29 ERROR (MainThread) [homeassistant.setup] Error during setup of component loxone
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/h11/_state.py", line 249, in _fire_event_triggered_transitions
    new_state = EVENT_TRIGGERED_TRANSITIONS[role][state][event_type]
KeyError: <class 'h11._events.ConnectionClosed'>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 193, in _async_setup_component
    result = await asyncio.wait_for(task, SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/loxone/__init__.py", line 201, in async_setup
    request_code = await lox_config.getJson()
  File "/config/custom_components/loxone/__init__.py", line 115, in getJson
    verify=False, timeout=TIMEOUT)
  File "/usr/local/lib/python3.7/site-packages/requests_async/api.py", line 11, in get
    return await request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests_async/api.py", line 6, in request
    return await session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests_async/sessions.py", line 79, in request
    resp = await self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests_async/sessions.py", line 136, in send
    r = await adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests_async/adapters.py", line 55, in send
    timeout=timeout,
  File "/usr/local/lib/python3.7/site-packages/http3/interfaces.py", line 49, in request
    return await self.send(request, verify=verify, cert=cert, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/http3/dispatch/connection_pool.py", line 130, in send
    raise exc
  File "/usr/local/lib/python3.7/site-packages/http3/dispatch/connection_pool.py", line 121, in send
    request, verify=verify, cert=cert, timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/http3/dispatch/connection.py", line 59, in send
    response = await self.h11_connection.send(request, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/http3/dispatch/http11.py", line 58, in send
    http_version, status_code, headers = await self._receive_response(timeout)
  File "/usr/local/lib/python3.7/site-packages/http3/dispatch/http11.py", line 130, in _receive_response
    event = await self._receive_event(timeout)
  File "/usr/local/lib/python3.7/site-packages/http3/dispatch/http11.py", line 161, in _receive_event
    event = self.h11_state.next_event()
  File "/usr/local/lib/python3.7/site-packages/h11/_connection.py", line 439, in next_event
    exc._reraise_as_remote_protocol_error()
  File "/usr/local/lib/python3.7/site-packages/h11/_util.py", line 72, in _reraise_as_remote_protocol_error
    raise self
  File "/usr/local/lib/python3.7/site-packages/h11/_connection.py", line 422, in next_event
    self._process_event(self.their_role, event)
  File "/usr/local/lib/python3.7/site-packages/h11/_connection.py", line 238, in _process_event
    self._cstate.process_event(role, type(event), server_switch_event)
  File "/usr/local/lib/python3.7/site-packages/h11/_state.py", line 238, in process_event
    self._fire_event_triggered_transitions(role, event_type)
  File "/usr/local/lib/python3.7/site-packages/h11/_state.py", line 253, in _fire_event_triggered_transitions
    .format(event_type.__name__, role, self.states[role]))
h11._util.RemoteProtocolError: can't handle event type ConnectionClosed when role=SERVER and state=SEND_RESPONSE
```

**Comment by Saviq** [comment]
Actually after a couple more trial and error cycles this started to work…
