### ISSUE TITLE
[Bug]: pyLoxone: Covers not working

### ISSUE THREAD

**Issue by Boss8472** [JoDehli/PyLoxone#304]
### Describe the bug

Just installed the pyLoxone Integration. After adding all loxone devices and entities to home assistant, I was testing the covers (Rollläden). It shows the wrong state (closed but was open) and the buttons have no affect (maybe because I cannot hat down as it was disabled).
I started the debug recording and saw some exception with loxone in call stack. Maybe that is related to my problem.

### Firmware of your Miniserver

14.2.6.16

### HomeAssistant install method

Home Assistant image on Raspi 4

### Version of HomeAssistant

2024.9.2

### Version of Pyloxone

Most recent (0.6.15)

### Update pyloxone

I installed the most recent version (0.6.15)

### Log

2024-09-21 20:06:08.304 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/lib/gmp', 'rb') inside the event loop by custom integration 'loxone' at custom_components/loxone/api.py, line 852: from Crypto.PublicKey import RSA (offender: /usr/local/lib/python3.12/ctypes/util.py, line 276: with open(filepath, 'rb') as fh:), please create a bug report at https://github.com/JoDehli/PyLoxone/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 752, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/loxone/__init__.py", line 415, in async_setup_entry
    res = await miniserver.start_ws()
  File "/config/custom_components/loxone/miniserver.py", line 123, in start_ws
    res = await self.api.async_init()
  File "/config/custom_components/loxone/api.py", line 393, in async_init
    rsa_gen = self.init_rsa_cipher()
  File "/config/custom_components/loxone/api.py", line 852, in init_rsa_cipher
    from Crypto.PublicKey import RSA

2024-09-21 20:06:08.318 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to glob with args ('/lib/libgmp.so',) inside the event loop by custom integration 'loxone' at custom_components/loxone/api.py, line 852: from Crypto.PublicKey import RSA (offender: /usr/local/lib/python3.12/ctypes/util.py, line 302: for f in glob('{0}{1}'.format(prefix, suffix)):), please create a bug report at https://github.com/JoDehli/PyLoxone/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#glob
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 752, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/loxone/__init__.py", line 415, in async_setup_entry
    res = await miniserver.start_ws()
  File "/config/custom_components/loxone/miniserver.py", line 123, in start_ws
    res = await self.api.async_init()
  File "/config/custom_components/loxone/api.py", line 393, in async_init
    rsa_gen = self.init_rsa_cipher()
  File "/config/custom_components/loxone/api.py", line 852, in init_rsa_cipher
    from Crypto.PublicKey import RSA

2024-09-21 20:06:08.331 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to iglob with args ('/lib/libgmp.so',) inside the event loop by custom integration 'loxone' at custom_components/loxone/api.py, line 852: from Crypto.PublicKey import RSA (offender: /usr/local/lib/python3.12/glob.py, line 28: return list(iglob(pathname, root_dir=root_dir, dir_fd=dir_fd, recursive=recursive,), please create a bug report at https://github.com/JoDehli/PyLoxone/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#iglob
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 752, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/loxone/__init__.py", line 415, in async_setup_entry
    res = await miniserver.start_ws()
  File "/config/custom_components/loxone/miniserver.py", line 123, in start_ws
    res = await self.api.async_init()
  File "/config/custom_components/loxone/api.py", line 393, in async_init
    rsa_gen = self.init_rsa_cipher()
  File "/config/custom_components/loxone/api.py", line 852, in init_rsa_cipher
    from Crypto.PublicKey import RSA

2024-09-21 20:06:08.363 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to scandir with args ('/lib',) inside the event loop by custom integration 'loxone' at custom_components/loxone/api.py, line 852: from Crypto.PublicKey import RSA (offender: /usr/local/lib/python3.12/glob.py, line 160: with os.scandir(arg) as it:), please create a bug report at https://github.com/JoDehli/PyLoxone/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#scandir
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 752, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/loxone/__init__.py", line 415, in async_setup_entry
    res = await miniserver.start_ws()
  File "/config/custom_components/loxone/miniserver.py", line 123, in start_ws
    res = await self.api.async_init()
  File "/config/custom_components/loxone/api.py", line 393, in async_init
    rsa_gen = self.init_rsa_cipher()
  File "/config/custom_components/loxone/api.py", line 852, in init_rsa_cipher
    from Crypto.PublicKey import RSA

**Comment by JoDehli** [comment]
@Boss8472 have restarted  home assistant after installation.

**Comment by JoDehli** [comment]
@Boss8472 do you still have this problem?

**Comment by Boss8472** [comment]
Now, after 2 days and some restart, covers are working as intended. Sorry for creating spam and thanks for you support.
