### ISSUE TITLE
Update to the newest HA version if you get this error: cannot import name 'AlarmControlPanelState' from 'homeassistant.components.alarm_control_panel'

### ISSUE THREAD

**Issue by prophylaxe** [JoDehli/PyLoxone#327]
### Describe the bug

This wasn't working for v0.6.16 either, now running pyloxone 0.7.0 and it is still there. Re-install didn't help, please see log below.
Let me know if you need anything else.

### Firmware of your Miniserver

15.2.10.14

### HomeAssistant install method

Hassio

### Version of HomeAssistant

2024.10.4

### Version of Pyloxone

0.7.0

### Update pyloxone

yes

### Log

Logger: homeassistant.config_entries
Quelle: config_entries.py:594
Erstmals aufgetreten: 19:59:26 (3 Vorkommnisse)
Zuletzt protokolliert: 20:00:18

Error setting up entry PyLoxone for loxone
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/loxone/__init__.py", line 193, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(config_entry, LOXONE_PLATFORMS)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2147, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  [Previous line repeated 8 more times]
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1165, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1090, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1264, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1296, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/loxone/alarm_control_panel.py", line 8, in <module>
    from homeassistant.components.alarm_control_panel import (
ImportError: cannot import name 'AlarmControlPanelState' from 'homeassistant.components.alarm_control_panel' (/usr/src/homeassistant/homeassistant/components/alarm_control_panel/__init__.py)

**Comment by JoDehli** [comment]
@prophylaxe update to the newest home assistant version..

**Comment by prophylaxe** [comment]
Thanks, forgot about that.
The latest HA update solved it again. So no more pyloxone errors anymore :)

**Comment by prophylaxe** [comment]
Thanks, forgot about that.
The latest HA update solved it again. So no more pyloxone errors anymore :)
