### ISSUE TITLE
[Bug]: KeyError in Loxone Alarm Control Panel 

### ISSUE THREAD

**Issue by knallt** [JoDehli/PyLoxone#335]
### Describe the bug

An error is occurring in the custom Loxone integration for Home Assistant, specifically in the alarm control panel component. The error suggests that there's an attempt to access a key 'armedAt' in a dictionary named 'states', but this key doesn't exist.
Error details:
Date and Time: 2024-11-18 10:44:15.453
Component: custom_components/loxone/alarm_control_panel.py
Line number: 112
Error type: KeyError

### Firmware of your Miniserver

12.2.12.01

### HomeAssistant install method

HAOS

### Version of HomeAssistant

[2024.11](https://www.home-assistant.io/blog/2024/11/06/release-202411/)

### Version of Pyloxone

0.7

### Update pyloxone

yes. On Vers 0.7

### Log

Settings for the log can be found on the main page under the section Log Configuration 2024-11-18 10:52:27.939 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/loxone/alarm_control_panel.py", line 112, in event_handler
    if self.states["armedAt"] in e.data:
       ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'armedAt'
Traceback (most recent call last):
  File "/config/custom_components/loxone/alarm_control_panel.py", line 112, in event_handler
    if self.states["armedAt"] in e.data:
       ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'armedAt'
2024-11-18 10:52:27.940 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/loxone/alarm_control_panel.py", line 112, in event_handler
    if self.states["armedAt"] in e.data:
       ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'armedAt'
2024-11-18 10:52:27.941 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/loxone/alarm_control_panel.py", line 112, in event_handler
    if self.states["armedAt"] in e.data:
       ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'armedAt'
Traceback (most recent call last):
  File "/config/custom_components/loxone/alarm_control_panel.py", line 112, in event_handler
    if self.states["armedAt"] in e.data:
       ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'armedAt'
2024-11-18 10:52:31.391 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/loxone/alarm_control_panel.py", line 112, in event_handler
    if self.states["armedAt"] in e.data:
       ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'armedAt'
2024-11-18 10:52:31.392 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/loxone/alarm_control_panel.py", line 112, in event_handler
    if self.states["armedAt"] in e.data:
       ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'armedAt'
2024-11-18 10:52:31.393 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/loxone/alarm_control_panel.py", line 112, in event_handler
    if self.states["armedAt"] in e.data:
       ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'armedAt'
2024-11-18 10:52:31.394 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/loxone/alarm_control_panel.py", line 112, in event_handler
    if self.states["armedAt"] in e.data:
       ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'armedAt'
Traceback (most recent call last):
  File "/config/custom_components/loxone/alarm_control_panel.py", line 112, in event_handler
    if self.states["armedAt"] in e.data:
       ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'armedAt'
2024-11-18 10:52:31.395 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/loxone/alarm_control_panel.py", line 112, in event_handler
    if self.states["armedAt"] in e.data:
       ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'armedAt'
2024-11-18 10:52:34.141 ERROR (Recorder) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/loxone/alarm_control_panel.py", line 112, in event_handler
    if self.states["armedAt"] in e.data:
       ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'armedAt'
2024-11-18 10:52:34.142 ERROR (Recorder) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/loxone/alarm_control_panel.py", line 112, in event_handler
    if self.states["armedAt"] in e.data:
       ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'armedAt'
2024-11-18 10:52:34.143 ERROR (Recorder) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/loxone/alarm_control_panel.py", line 112, in event_handler
    if self.states["armedAt"] in e.data:
       ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'armedAt'
2024-11-18 10:52:34.144 ERROR (Recorder) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/loxone/alarm_control_panel.py", line 112, in event_handler
    if self.states["armedAt"] in e.data:
       ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'armedAt'
Traceback (most recent call last):
  File "/config/custom_components/loxone/alarm_control_panel.py", line 112, in event_handler
    if self.states["armedAt"] in e.data:
       ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'armedAt'
2024-11-18 10:52:34.145 ERRO

**Comment by JoDehli** [comment]
@knallt you have a very old Firmware on your loxone. Please update your loxone and the error should be gone.

**Comment by knallt** [comment]
hm, you're right. works! Thx! @JoDehli
