### ISSUE TITLE
Integration not loading

### ISSUE THREAD

**Issue by pissten** [JoDehli/PyLoxone#341]
### Describe the bug

Integration not loading anymore, after upgrade to 0.7.1 
Tried to revert back to 0.7.0 but the integration won't load.
Have also tried uninstalling the pyloxone from HACS, removed the integration and manually deleted the folder
under /config/custom_components/loxone

### Firmware of your Miniserver

Latest (15.2.10.14)

### HomeAssistant install method

Docker HA Core. Installed Loxone using HACS

### Version of HomeAssistant

2024.10.4

### Version of Pyloxone

0.7.1

### Update pyloxone

yes

### Log

Logger: homeassistant.config_entries
Kilde: config_entries.py:594
Førs oppstått: 11:55:23 (3 hendelser)
Sist logget: 11:56:48

Error setting up entry PyLoxone for loxone
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/loxone/__init__.py", line 193, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(config_entry, LOXONE_PLATFORMS)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2147, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  [Previous line repeated 1 more time]
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1165, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1090, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1264, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1296, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/loxone/alarm_control_panel.py", line 8, in <module>
    from homeassistant.components.alarm_control_panel import (
ImportError: cannot import name 'AlarmControlPanelState' from 'homeassistant.components.alarm_control_panel' (/usr/src/homeassistant/homeassistant/components/alarm_control_panel/__init__.py)

**Comment by JoDehli** [comment]
@pissten any success?

**Comment by pissten** [comment]
> @pissten any success?

Ahhh. I feel so stupid now 🙈 it was indeed because of the integration version didn't match with my ha version. Reverted back to 0.6.x and it worked again. Apologies for the unnecessary bug report
