### ISSUE TITLE
Error in HA logs : Error while setting up loxone platform for scene

### ISSUE THREAD

**Issue by kalhimeo** [JoDehli/PyLoxone#37]
Dear developer,

Thank you very much for your integration !

Unfortunately I have this error in my HA log at every restart :

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/loxone/scene.py", line 46, in async_setup_platform
    async_call_later(hass, 0.5, async_call())
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1179, in async_call_later
    return async_track_point_in_utc_time(
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1133, in async_track_point_in_utc_time
    job = action if isinstance(action, HassJob) else HassJob(action)
  File "/usr/src/homeassistant/homeassistant/core.py", line 174, in __init__
    raise ValueError("Coroutine not allowed to be passed to HassJob")
ValueError: Coroutine not allowed to be passed to HassJob`

I am running HA 118.0, PyLoxone 0.2.7 (generate_scenes: true), Loxone Config 11.1.9.14

Let me know if you need more infos from my Loxone configuration.

Thanks !

**Comment by JoDehli** [comment]
I released a new version a few seconds ago. Please update to this version. If error is gone please close the issue.

**Comment by kalhimeo** [comment]
Error seems to be gone, thank you very much :-)
