### ISSUE TITLE
Error adding entities for domain sensor with platform loxone

### ISSUE THREAD

**Issue by vicfalls** [JoDehli/PyLoxone#43]
Error occurs since the installation of the latest Home Assistant OS 5.8!

Logger: homeassistant.components.sensor
Source: custom_components/loxone/sensor.py:247 
Integration: Sensor (documentation, issues) 
First occurred: 19:57:49 (2 occurrences) 
Last logged: 19:57:49

Error adding entities for domain sensor with platform loxone
Error while setting up loxone platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 316, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 531, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state
    sstate = self.state
  File "/config/custom_components/loxone/sensor.py", line 247, in state
    return self._format % self._state
TypeError: must be real number, not str

**Comment by JoDehli** [comment]
It has nothing to do with the version. I came with the last version. I fix it in the next version. But this time
I test it before release. Irgone the errors all sensors should work with the error.

**Comment by vicfalls** [comment]
Thanks for the update....

**Comment by JoDehli** [comment]
Please try the newest version.
