### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by madislammergas** [JoDehli/PyLoxone#48]
Hi,

During startup I get an error. If I use same ip, port, username and pwd, I can access miniserver from browser (also openHAB connects).

Error message:
`2021-01-29 10:58:08 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry PyLoxone for loxone
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests_async/adapters.py", line 48, in send
    response = await self.pool.request(
  File "/usr/local/lib/python3.8/site-packages/http3/interfaces.py", line 49, in request
    return await self.send(request, verify=verify, cert=cert, timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/http3/dispatch/connection_pool.py", line 130, in send
    raise exc
  File "/usr/local/lib/python3.8/site-packages/http3/dispatch/connection_pool.py", line 120, in send
    response = await connection.send(
  File "/usr/local/lib/python3.8/site-packages/http3/dispatch/connection.py", line 53, in send
    await self.connect(verify=verify, cert=cert, timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/http3/dispatch/connection.py", line 81, in connect
    reader, writer, protocol = await self.backend.connect(
  File "/usr/local/lib/python3.8/site-packages/http3/concurrency.py", line 204, in connect
    stream_reader, stream_writer = await asyncio.wait_for(  # type: ignore
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 494, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.8/asyncio/streams.py", line 52, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 986, in create_connection
    infos = await self._ensure_resolved(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1365, in _ensure_resolved
    return await loop.getaddrinfo(host, port, family=family, type=type,
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 825, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/loxone/__init__.py", line 122, in async_setup_entry
    if not await miniserver.async_setup():
  File "/config/custom_components/loxone/miniserver.py", line 118, in async_setup
    request_code = await self.lox_config.getJson()
  File "/config/custom_components/loxone/api.py", line 60, in getJson
    api_resp = await requests.get(url_api,
  File "/usr/local/lib/python3.8/site-packages/requests_async/api.py", line 11, in get
    return await request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests_async/api.py", line 6, in request
    return await session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests_async/sessions.py", line 79, in request
    resp = await self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests_async/sessions.py", line 136, in send
    r = await adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests_async/adapters.py", line 58, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: [Errno -3] Try again`

**Comment by JoDehli** [comment]
Thanks for creating the issue. Which port do you use?

**Comment by madislammergas** [comment]
I use 61400. This is the port that I see in web browser after ip address.

**Comment by JoDehli** [comment]
And you use hassio on the newest version or is it a manual Installation? Are you familiar with programming? Especially python?

**Comment by madislammergas** [comment]
I use Hassio 5.10, it is not manual installation. I know Python a little.

**Comment by JoDehli** [comment]
Ok let me think about it. Maybe I can make you a little script to test all the different steps and we can find out where exactly the problems accurs. What you can do is they a different port.

**Comment by madislammergas** [comment]
I have tried 80 and 8080 as well and I tried to add http:// front of ip address in config.

**Comment by madislammergas** [comment]
I do not know does it make any difference but I get the same error if I remove "loxone: ..." config from configuration.yaml.

**Comment by JoDehli** [comment]
Completely remove anything from the yaml. Only configure offer the integration menue

**Comment by JoDehli** [comment]
Of course restart after each change. The new settings will be read in start of home assistant

**Comment by madislammergas** [comment]
Thanks, this was the case. I assumed that I need to use configuration.yaml. Now it works
