### ISSUE TITLE
Lost connection to Loxone since the last update

### ISSUE THREAD

**Issue by jdenver13** [JoDehli/PyLoxone#59]
Not sure if I missed any breaking changes but I no longer have a connection to Loxone after updating via HACS today. Im running the latest version of home assistant and have gen1 loxone.

```
Logger: homeassistant.config_entries
Source: custom_components/loxone/api.py:361 
First occurred: 19:10:49 (1 occurrences) 
Last logged: 19:10:49

Error setting up entry PyLoxone for loxone
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 248, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/loxone/__init__.py", line 131, in async_setup_entry
    if not await miniserver.async_setup():
  File "/config/custom_components/loxone/miniserver.py", line 111, in async_setup
    res = await self.api.async_init()
  File "/config/custom_components/loxone/api.py", line 361, in async_init
    await self._ws.send(enc_command)
  File "/usr/local/lib/python3.8/site-packages/websockets/protocol.py", line 555, in send
    await self.ensure_open()
  File "/usr/local/lib/python3.8/site-packages/websockets/protocol.py", line 812, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: code = 1000 (OK), reason = normally closed

```
Any help would be appreciated

**Comment by Juxz** [comment]
Same issue here

**Comment by JoDehli** [comment]
@Juxz and @jdenver13  which Loxone Firmware do you use? 
Please downgrade for now. On my system it works and I can not find out why? Maybe you 
have not the latest firmware from loxone?

**Comment by jdenver13** [comment]
Im using 12.0.2.24 but after the new update today, the problems now solved. Thank you.

**Comment by JoDehli** [comment]
@Juxz which version do use? Less than version 12?

**Comment by Juxz** [comment]
Yes, my miniserver is still running 11.1.9.14

**Comment by JoDehli** [comment]
@Juxz you try the newest 0.3.3 if you want. Should now work with your old firmware.

**Comment by Juxz** [comment]
Thanks, will try asap

**Comment by Juxz** [comment]
I was not able to make the 0.3.3 work so far.
I also upgraded my miniserver to 12.0.2.24, but even though it works only with 0.3.2.

Always the same error log:

```
Logger: homeassistant.config_entries
Source: custom_components/loxone/api.py:369 
First occurred: 21:56:38 (1 occurrences) 
Last logged: 21:56:38

Error setting up entry PyLoxone for loxone
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 248, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/loxone/__init__.py", line 131, in async_setup_entry
    if not await miniserver.async_setup():
  File "/config/custom_components/loxone/miniserver.py", line 111, in async_setup
    res = await self.api.async_init()
  File "/config/custom_components/loxone/api.py", line 369, in async_init
    await self._ws.send(enc_command)
  File "/usr/local/lib/python3.8/site-packages/websockets/protocol.py", line 555, in send
    await self.ensure_open()
  File "/usr/local/lib/python3.8/site-packages/websockets/protocol.py", line 812, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: code = 1000 (OK), reason = normally closed


```

**Comment by JoDehli** [comment]
@Juxz have you tried it multiple times after you got this error? Because when the token is old or from a former firmware version I delete it. Then you must restart again and a new token is generated.

**Comment by bartn80** [comment]
@JoDehli - I'm facing similar issues with Loxone firmware 12.0.2.24 and 0.3.3 (also tried 0.3.2).

When using the local IP address of the miniserver, I get the following errors:

2021-04-07 10:23:32 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry PyLoxone for loxone
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 248, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/loxone/__init__.py", line 131, in async_setup_entry
    if not await miniserver.async_setup():
  File "/config/custom_components/loxone/miniserver.py", line 111, in async_setup
    res = await self.api.async_init()
  File "/config/custom_components/loxone/api.py", line 369, in async_init
    await self._ws.send(enc_command)
  File "/usr/local/lib/python3.8/site-packages/websockets/protocol.py", line 555, in send
    await self.ensure_open()
  File "/usr/local/lib/python3.8/site-packages/websockets/protocol.py", line 812, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: code = 1000 (OK), reason = normally closed

When using the Loxone cloud address, I get the following errors:
2021-04-07 10:34:26 ERROR (MainThread) [custom_components.loxone.api] Could not connect to Loxone! Status code 500.
2021-04-07 10:34:26 ERROR (MainThread) [custom_components.loxone.miniserver] Error connecting to loxone miniserver #2 Code (False)

When directly opening the loxone cloud address in a browser, I redirects to the Loxone web interface just fine, and I'm able to log on with the same user credentials as configured in the PyLoxone configuration.

Any help more than appreciated ;)

**Comment by JoDehli** [comment]
Please try the updated 0.3.3 version and give feedback if it worked. My problem is that I can not reproduce the problems which some of the users have since the the new firmware released.

**Comment by Juxz** [comment]
Works great on my end!

**Comment by JoDehli** [comment]
Yes for the gen2 you need to use the cloud address.

**Comment by bartn80** [comment]
Ok clear, then I'm back to the following error messages, which hint to a plain connection/authentication issue:

2021-04-07 10:34:26 ERROR (MainThread) [custom_components.loxone.api] Could not connect to Loxone! Status code 500.
2021-04-07 10:34:26 ERROR (MainThread) [custom_components.loxone.miniserver] Error connecting to loxone miniserver #2 Code (False)

I'll keep you posted if I find the solution ;)

**Comment by JoDehli** [comment]
You can try to get to the address via browser. Did you reach the loxone login page?

**Comment by bartn80** [comment]
Yes, that's all working fine: if I open the loxone cloud address in a web browser, it correctly redirects to the loxone login page, and afterwards I can correctly log-on to it with the same account/password that are configured in the PyLoxone config in HA.

And yes, after changing anything in the Pyloxone config settings, I manually remove the loxone token file and do a restart of HA ;)

The Loxone documentation mentions that status code 500 is related to "Malformed Json: the request is not in the expected format", so I've justed looked into that: manually retieved the Json file from http://{ip-address-of-your-loxone}:{port}/data/LoxAPP3.json, opened it in a Json validator, and got confirmation that the format is perfectly fine...

**Comment by bartn80** [comment]
Yes, port forwarding is correctly configured. I have access to loxone from everywhere.
I've also just tried accessing the loxone web application on my Phone with Wifi turned off, and by using the Loxone cloud url, and again that works fine.

**Comment by JoDehli** [comment]
Ok I have ask a other user which has a gen2 and he have all ports closed so that should not be the problem.

Maybe you can write me directly via email. joachim.dehli@gmail.com
