### ISSUE TITLE
Recursion Error upon reconnect

### ISSUE THREAD

**Issue by arjenvrh** [JoDehli/PyLoxone#6]
Hi

First of all, thanks for the great library! 

Occasionally, after running the integration for several days, I am getting a recursion error. See the log below. 

It seems the reconnect and start functions are calling each other recursively. I'm not quite sure what's going on in this code and what triggers the reconnect, but on the surface it seems like self.start calls self.reconnect, and when self._state is set to "CONNECTED" in self.async_init self.start is called again, which checks that the state is not "STOPPING" and calls reconnect again. I tried adding an additional check to prevent the reconnect function being called when the state is "CONNECTED", unfortunately, this did not work (it prevent the recursion but after about 1.5 hours I'm getting an ConnectionClosed Exception within send_websocket_command). 

As stated, I am not quite familiar with the connection / reconnection code, perhaps you have a better feeling what the problem could be? 

Regards
Arjen

Stacktrace:
-----------
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/loxone/__init__.py", line 525, in reconnect
    await self.start()
  File "/config/custom_components/loxone/__init__.py", line 518, in start
    res = await self.reconnect()
  File "/config/custom_components/loxone/__init__.py", line 525, in reconnect
    await self.start()
  File "/config/custom_components/loxone/__init__.py", line 518, in start
    res = await self.reconnect()
  File "/config/custom_components/loxone/__init__.py", line 523, in reconnect
    res = await self.async_init()
  File "/config/custom_components/loxone/__init__.py", line 560, in async_init
    resp = self.get_public_key()
  File "/config/custom_components/loxone/__init__.py", line 943, in get_public_key
    response = requests.get(command, auth=(self._username, self._pasword))
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 330, in begin
    self.headers = self.msg = parse_headers(self.fp)
  File "/usr/local/lib/python3.7/http/client.py", line 224, in parse_headers
    return email.parser.Parser(_class=_class).parsestr(hstring)
  File "/usr/local/lib/python3.7/email/parser.py", line 68, in parsestr
    return self.parse(StringIO(text), headersonly=headersonly)
  File "/usr/local/lib/python3.7/email/parser.py", line 57, in parse
    feedparser.feed(data)
  File "/usr/local/lib/python3.7/email/feedparser.py", line 176, in feed
    self._call_parse()
  File "/usr/local/lib/python3.7/email/feedparser.py", line 180, in _call_parse
    self._parse()
  File "/usr/local/lib/python3.7/email/feedparser.py", line 295, in _parsegen
    if self._cur.get_content_maintype() == 'message':
  File "/usr/local/lib/python3.7/email/message.py", line 594, in get_content_maintype
    ctype = self.get_content_type()
  File "/usr/local/lib/python3.7/email/message.py", line 578, in get_content_type
    value = self.get('content-type', missing)
  File "/usr/local/lib/python3.7/email/message.py", line 471, in get
    return self.policy.header_fetch_parse(k, v)
  File "/usr/local/lib/python3.7/email/_policybase.py", line 316, in header_fetch_parse
    return self._sanitize_header(name, value)
  File "/usr/local/lib/python3.7/email/_policybase.py", line 287, in _sanitize_header
    if _has_surrogates(value):
  File "/usr/local/lib/python3.7/email/utils.py", line 57, in _has_surrogates
    s.encode()
RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by JoDehli** [comment]
Can you give me more informations when this happens? Have you got a stable connection? I can not reproduce this error. There are errors on your log which are not from the loxone? Did you change something the last days?

**Comment by arjenvrh** [comment]
The issue occurs every couple of days, in the meantime everything is running stable. The Loxone App keeps on working, and I don’t get any notification from the Loxone server that there was any problem. 

I edited the stack trace in the original message, in the complete trace there’s a lot more calls between reconnect and start. I don’t quite understand where the call to start/reconnect comes from, as far as I can tell start is only called upon HA start?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JoDehli** [comment]
I uploaded a new version with improved reconnect. I tried it by disconnect my dev pc from the network. For me it worked now really reliable. Maybe this fixes your issue. 

I must be something with the connection. The start routine is called when it tries to reconnect.

**Comment by arjenvrh** [comment]
Wow that was a fast update. I've just updated and restarted HA, I'll keep it running over the next few days and get back to you. Thanks again!

**Comment by arjenvrh** [comment]
It seems to be running stable with the improved reconnect. Great work, looking forward to test the new alarm control panel!
