### ISSUE TITLE
Error in setting up

### ISSUE THREAD

**Issue by jzeeman01** [JoDehli/PyLoxone#81]
Hi 
Couple of month ago I started using Hassio in a VM (previously had it on a pi for about 2 years - PyLoxone since you brought it out)
Everything else (other HACS integrations) work fine - its just PyLoxone :-(
Any help or pointers would be much appreciated

Rgds
J

Error setting up entry PyLoxone for loxone

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/streams.py", line 52, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/http3/concurrency.py", line 204, in connect
    stream_reader, stream_writer = await asyncio.wait_for(  # type: ignore
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

**Comment by JoDehli** [comment]
@jzeeman01 have you configured it over the gui or over the yaml?

**Comment by jzeeman01** [comment]
Hi @JoDehli 
I configured it via the gui - its an old version 1 miniserver so just ip address/user/pass/port
Rgds
Jacques

**Comment by jzeeman01** [comment]
Needed to change to port 80
