### ISSUE TITLE
Unable to add switch in Home Assistant

### ISSUE THREAD

**Issue by elRadix** [JoDehli/PyLoxone#90]
Created a switch in loxone config but does not show in home assistant, I get the error below

![image](https://user-images.githubusercontent.com/6258894/145709288-28d1037d-3fa8-4412-9b2e-15b373b2e00d.png)

```

Logger: homeassistant.components.switch
Source: custom_components/loxone/switch.py:288
Integration: Switch (documentation, issues)
First occurred: 11:33:46 (2 occurrences)
Last logged: 11:33:46

Error adding entities for domain switch with platform loxone
Error while setting up loxone platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 457, in _async_add_entity
    device_info = entity.device_info
  File "/config/custom_components/loxone/switch.py", line 288, in device_info
    "model": self.typ,
AttributeError: 'LoxoneSwitch' object has no attribute 'typ'
```

**Comment by JoDehli** [comment]
Have you tried the newest beta release?

**Comment by elRadix** [comment]
solved with the latest release
thank you!
